### ISSUE TITLE
Crear endpoint para obtener información de la finca

### ISSUE THREAD

**Issue by damianfanaro** [igrowker/i003-adoptree-back#4]
Desarrollar el endpoint GET /api/finca que proporcione información detallada sobre la finca donde se cultiva el árbol adoptado. Asegurarse de que los datos, como las prácticas sostenibles y la ubicación de la finca, estén correctamente organizados.

**Comment by JuanPedro2323** [comment]
Se ha probado el endpoint GET /api/finca y funciona correctamente. 
- Se crearon dos nuevas fincas y se verificó que la respuesta devuelve la información correcta.
- El endpoint devuelve un status 200 OK con los datos esperados.

Todo funciona según lo esperado.
